#!/usr/bin/env bash
set -euo pipefail

# Launches Roblox Studio's built-in MCP server process (StudioMCP.exe, generated by
# Studio itself once Assistant's "Enable Studio as MCP server" toggle is switched on —
# see SETUP.md's "Studio MCP over the network" section). Invoked as the --stdio command
# by mcp-bridge.sh/supergateway.
#
# Deliberately invokes StudioMCP.exe directly under Wine rather than going through the
# mcp.bat launcher Studio also generates (%LOCALAPPDATA%\Roblox\mcp.bat — the path
# Roblox's own docs point Windows/macOS MCP clients at): mcp.bat's if/else has a real
# cmd.exe batch bug (the `else` sits on its own line instead of the same line as the
# preceding `)`, which cmd.exe's batch parser requires). Confirmed via direct testing:
# it still runs StudioMCP.exe fine on the common path (the hardcoded version folder
# exists), but throws a stray "Syntax error: unexpected ELSE" once that process exits
# and control returns to the batch script. Harmless on its own, but not worth risking
# that text ever landing in the stdio stream supergateway parses as newline-delimited
# JSON-RPC. Resolving the current version folder ourselves (glob + most-recently-
# modified) gets mcp.bat's one genuinely useful property — surviving a Vinegar/Studio
# version bump without a hardcoded path — without going through cmd.exe at all.

export WINEPREFIX="/root/.local/share/vinegar/prefixes/studio"
export PATH="/root/.local/share/vinegar/kombucha/bin:${PATH}"

STUDIO_MCP_EXE="$(ls -td /root/.local/share/vinegar/versions/*/StudioMCP.exe 2>/dev/null | head -n1)"
if [[ -z "${STUDIO_MCP_EXE}" ]]; then
  echo "[studio-mcp-stdio] StudioMCP.exe not found under /root/.local/share/vinegar/versions/*/ — has Studio's Assistant > Manage MCP Servers > 'Enable Studio as MCP server' been toggled on at least once? See SETUP.md." >&2
  exit 1
fi

exec wine "${STUDIO_MCP_EXE}"
