#!/usr/bin/env bash
set -euo pipefail

# Launches Roblox Studio's built-in MCP server process (StudioMCP.exe, generated by
# Studio itself once Assistant's "Enable Studio as MCP server" toggle is switched on —
# see SETUP.md's "Studio MCP over the network" section). Invoked as the --stdio command
# by mcp-bridge.sh/supergateway.
#
# Deliberately invokes StudioMCP.exe directly under Wine rather than going through the
# mcp.bat launcher Studio also generates (%LOCALAPPDATA%\Roblox\mcp.bat — the path
# Roblox's own docs point Windows/macOS MCP clients at): mcp.bat's if/else has a real
# cmd.exe batch bug (the `else` sits on its own line instead of the same line as the
# preceding `)`, which cmd.exe's batch parser requires). Confirmed via direct testing:
# it still runs StudioMCP.exe fine on the common path (the hardcoded version folder
# exists), but throws a stray "Syntax error: unexpected ELSE" once that process exits
# and control returns to the batch script. Harmless on its own, but not worth risking
# that text ever landing in the stdio stream supergateway parses as newline-delimited
# JSON-RPC. Resolving the current version folder ourselves (glob + most-recently-
# modified) gets mcp.bat's one genuinely useful property — surviving a Vinegar/Studio
# version bump without a hardcoded path — without going through cmd.exe at all.

export WINEPREFIX="/root/.local/share/vinegar/prefixes/studio"

# Studio를 띄우는 데 쓰이는 것과 **같은** wine을 써야 한다. 그 답은 Vinegar 자신의
# config.toml에 있다: `wineroot`가 설정돼 있으면 Vinegar는 그 경로의 wine을 쓰고,
# 없으면 자기가 직접 받아 관리하는 ~/.local/share/vinegar/kombucha를 쓴다.
#
# 예전에는 후자를 PATH에 하드코딩했는데, wine 11.16 뷰포트 회귀 때문에 wine 11.15를
# /opt/kombucha-pinned에 굽고 config.toml에 wineroot로 핀을 박자 이 스크립트만 옛
# 경로를 보게 됐다 - `exec: wine: not found`로 자식이 code=127로 죽고, 브리지 자체는
# 멀쩡히 살아있어서 원격에서는 "인증은 통과하는데 응답이 없는" 타임아웃으로만 보였다.
# 그래서 경로를 또 하나 하드코딩하는 대신 진짜 출처를 읽는다 - 나중에 핀을 풀어도
# 여기를 다시 고칠 일이 없다.
VINEGAR_CONFIG="${HOME:-/root}/.config/vinegar/config.toml"
WINE_BIN=""

if [[ -f "${VINEGAR_CONFIG}" ]]; then
  WINEROOT="$(sed -n 's/^[[:space:]]*wineroot[[:space:]]*=[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' "${VINEGAR_CONFIG}" | tail -n1)"
  if [[ -n "${WINEROOT}" && -x "${WINEROOT}/bin/wine" ]]; then
    WINE_BIN="${WINEROOT}/bin/wine"
  fi
fi

if [[ -z "${WINE_BIN}" && -x /root/.local/share/vinegar/kombucha/bin/wine ]]; then
  WINE_BIN="/root/.local/share/vinegar/kombucha/bin/wine"
fi

if [[ -z "${WINE_BIN}" ]]; then
  WINE_BIN="$(command -v wine || true)"
fi

if [[ -z "${WINE_BIN}" ]]; then
  echo "[studio-mcp-stdio] no wine binary found - looked at wineroot in ${VINEGAR_CONFIG}, then /root/.local/share/vinegar/kombucha/bin/wine, then \$PATH. Has Vinegar downloaded (or has the Dockerfile pinned) a Wine build yet?" >&2
  exit 1
fi

export PATH="$(dirname "${WINE_BIN}"):${PATH}"

STUDIO_MCP_EXE="$(ls -td /root/.local/share/vinegar/versions/*/StudioMCP.exe 2>/dev/null | head -n1)"
if [[ -z "${STUDIO_MCP_EXE}" ]]; then
  echo "[studio-mcp-stdio] StudioMCP.exe not found under /root/.local/share/vinegar/versions/*/ — has Studio's Assistant > Manage MCP Servers > 'Enable Studio as MCP server' been toggled on at least once? See SETUP.md." >&2
  exit 1
fi

exec "${WINE_BIN}" "${STUDIO_MCP_EXE}"
