#!/usr/bin/env bash
set -euo pipefail

# Launches Roblox Studio's built-in MCP server process (StudioMCP.exe, generated by
# Studio itself once Assistant's "Enable Studio as MCP server" toggle is switched on —
# see SETUP.md's "Studio MCP over the network" section). Invoked as the --stdio command
# by mcp-bridge.sh/supergateway.
#
# Deliberately invokes StudioMCP.exe directly under Wine rather than going through the
# mcp.bat launcher Studio also generates (%LOCALAPPDATA%\Roblox\mcp.bat — the path
# Roblox's own docs point Windows/macOS MCP clients at): mcp.bat's if/else has a real
# cmd.exe batch bug (the `else` sits on its own line instead of the same line as the
# preceding `)`, which cmd.exe's batch parser requires). Confirmed via direct testing:
# it still runs StudioMCP.exe fine on the common path (the hardcoded version folder
# exists), but throws a stray "Syntax error: unexpected ELSE" once that process exits
# and control returns to the batch script. Harmless on its own, but not worth risking
# that text ever landing in the stdio stream supergateway parses as newline-delimited
# JSON-RPC. Resolving the current version folder ourselves (glob + most-recently-
# modified) gets mcp.bat's one genuinely useful property — surviving a Vinegar/Studio
# version bump without a hardcoded path — without going through cmd.exe at all.

# Studio를 띄우는 것과 **같은** wine을 써야 한다 - 어떻게 찾는지, 왜 하드코딩하면 안 되는지는
# studio-wine.sh에 있다(desktop-resize도 같은 함수를 쓴다).
. /etc/roblox-studio/studio-wine.sh
export WINEPREFIX="${STUDIO_WINEPREFIX}"
WINE_BIN="$(studio_wine_bin || command -v wine || true)"

if [[ -z "${WINE_BIN}" ]]; then
  echo "[studio-mcp-stdio] no wine binary found - looked at wineroot in ${VINEGAR_CONFIG}, then /root/.local/share/vinegar/kombucha/bin/wine, then \$PATH. Has Vinegar downloaded (or has the Dockerfile pinned) a Wine build yet?" >&2
  exit 1
fi

export PATH="$(dirname "${WINE_BIN}"):${PATH}"

STUDIO_MCP_EXE="$(ls -td /root/.local/share/vinegar/versions/*/StudioMCP.exe 2>/dev/null | head -n1)"
if [[ -z "${STUDIO_MCP_EXE}" ]]; then
  echo "[studio-mcp-stdio] StudioMCP.exe not found under /root/.local/share/vinegar/versions/*/ — has Studio's Assistant > Manage MCP Servers > 'Enable Studio as MCP server' been toggled on at least once? See SETUP.md." >&2
  exit 1
fi

exec "${WINE_BIN}" "${STUDIO_MCP_EXE}"
